version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
    depends_on:
      - frontend
  frontend: 
    image: "mahmudarif/welcome-app:latest"
    restart: always

