version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    restart: always
  frontend: 
    image: "mahmudarif/welcome-app:latest"
    command: >
      sh -c "cd my-project && yarn && yarn run build && yarn run start"
    restart: always
    